dotnet add package CodeMechanic.Diagnostics
dotnet add package CodeMechanic.FileSystem
dotnet add package CodeMechanic.Scriptures
dotnet add package CodeMechanic.Systemd.Daemons
dotnet add package CodeMechanic.Todoist
dotnet add package CodeMechanic.Types
dotnet add package Coravel
dotnet add package Microsoft.Extensions.Hosting
dotnet add package Microsoft.Extensions.Hosting.Systemd
